/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package surat;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import koneksi.Koneksi;

/**
 *
 * @author Fazar
 */
public class Disposisi extends javax.swing.JFrame {

    /**
     * Creates new form Disposisi
     */
    Connection conn = new Koneksi().connect();
    Statement state;
    PreparedStatement prepStat;
    ResultSet res;
    
    public Disposisi() {
        initComponents();
        noSurat.enable(false);
        isiPrihal.enable(false);
        jenisSurat.enable(false);
        tanggal.enable(false);
        pendisposisian.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnDisposisi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tujuanDisposisi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        isiPrihal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        statusSurat = new javax.swing.JComboBox<>();
        instruksi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jenisSurat = new javax.swing.JTextField();
        btnTutup = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnPenyegaran = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pendisposisian = new javax.swing.JTextField();
        noSurat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tanggal = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnDisposisi.setBackground(new java.awt.Color(255, 102, 0));
        pnDisposisi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informasi Surat", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel1.setText("No.Surat");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setText("Tanggal Surat");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel3.setText("Isi Prihal");

        tujuanDisposisi.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel7.setText("Tujuan Disposisi");

        isiPrihal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiPrihalActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel9.setText("Status Surat");

        statusSurat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        statusSurat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DITERIMA", "DITOLAK" }));

        instruksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instruksiActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel12.setText("Jenis Surat");

        btnTutup.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/New folder/20170201232233.png"))); // NOI18N
        btnTutup.setText("TUTUP");
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/New folder/simpan.2.png"))); // NOI18N
        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnPenyegaran.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPenyegaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/New folder/tambah2.png"))); // NOI18N
        btnPenyegaran.setText("PENYEGARAN");
        btnPenyegaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenyegaranActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel15.setText("Instruksi");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel16.setText("Pendisposisian");

        pendisposisian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendisposisianActionPerformed(evt);
            }
        });

        noSurat.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("DISPOSISI SURAT");

        javax.swing.GroupLayout pnDisposisiLayout = new javax.swing.GroupLayout(pnDisposisi);
        pnDisposisi.setLayout(pnDisposisiLayout);
        pnDisposisiLayout.setHorizontalGroup(
            pnDisposisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDisposisiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDisposisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addGroup(pnDisposisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnDisposisiLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(108, 108, 108)
                            .addComponent(statusSurat, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnDisposisiLayout.createSequentialGroup()
                            .addGroup(pnDisposisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnDisposisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tujuanDisposisi)
                                .addComponent(instruksi, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnDisposisiLayout.createSequentialGroup()
                        .addGroup(pnDisposisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16)
                            .addComponent(jLabel2))
                        .addGap(93, 93, 93)
                        .addGroup(pnDisposisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jenisSurat)
                            .addComponent(isiPrihal)
                            .addComponent(pendisposisian)
                            .addComponent(noSurat)
                            .addComponent(tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                    .addGroup(pnDisposisiLayout.createSequentialGroup()
                        .addComponent(btnTutup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnDisposisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(pnDisposisiLayout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPenyegaran)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDisposisiLayout.setVerticalGroup(
            pnDisposisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDisposisiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addGroup(pnDisposisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(noSurat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pnDisposisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(isiPrihal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDisposisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jenisSurat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDisposisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pnDisposisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(pendisposisian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pnDisposisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusSurat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDisposisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tujuanDisposisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnDisposisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(instruksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnDisposisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTutup)
                    .addComponent(btnSimpan)
                    .addComponent(btnPenyegaran))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnDisposisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnDisposisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isiPrihalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiPrihalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isiPrihalActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

   
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try{
            SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
            String tgl = String.valueOf(fmt.format(tanggal.getDate()));
            String sql = "INSERT INTO disposisi_surat (surat_masuk_id, surat_keluar_id, no_surat, isi_prihal, jenis_surat, tanggal, pendisposisian, tujuan_disposisi, instruksi, status) VALUES (?,?,?,?,?,?,?,?,?,?)";
            prepStat = conn.prepareStatement(sql);
            int id = -1;
            
            if(pendisposisian.getText().equalsIgnoreCase("masuk")) {
                String queryMasuk = "SELECT id FROM surat_masuk WHERE no_surat = ?";
                PreparedStatement stmtMasuk = conn.prepareStatement(queryMasuk);
                stmtMasuk.setString(1, noSurat.getText());
                ResultSet rsMasuk = stmtMasuk.executeQuery();
                if (rsMasuk.next()) {
                    id = rsMasuk.getInt("id");
                }
                prepStat.setInt(1, id);
                prepStat.setInt(2, -1);
            }else {
                String queryMasuk = "SELECT id FROM surat_keluar WHERE no_surat = ?";
                PreparedStatement stmtMasuk = conn.prepareStatement(queryMasuk);
                stmtMasuk.setString(1, noSurat.getText());
                ResultSet rsMasuk = stmtMasuk.executeQuery();
                if (rsMasuk.next()) {
                    id = rsMasuk.getInt("id");
                }
                prepStat.setInt(1, -1);
                prepStat.setInt(2, id);
            }
            prepStat.setString(3, noSurat.getText());
            prepStat.setString(4, isiPrihal.getText());
            prepStat.setString(5, jenisSurat.getText());
            prepStat.setString(6, tgl);
            prepStat.setString(7, pendisposisian.getText());
            prepStat.setString(8, tujuanDisposisi.getText() );
            prepStat.setString(9, instruksi.getText());
            prepStat.setString(10, statusSurat.getSelectedItem().toString());
            prepStat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            dispose();
        }catch (Exception t){
            JOptionPane.showMessageDialog(null,"Data Gagal Disimpan");
            System.out.print(t);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void inputRefresh() {
        statusSurat.setSelectedIndex(0);
        tujuanDisposisi.setText("");
        instruksi.setText("");
    }
    
    private void btnPenyegaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenyegaranActionPerformed
        inputRefresh();
    }//GEN-LAST:event_btnPenyegaranActionPerformed

    private void instruksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instruksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instruksiActionPerformed

    private void pendisposisianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendisposisianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pendisposisianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Disposisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Disposisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Disposisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Disposisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Disposisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPenyegaran;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTutup;
    private javax.swing.JTextField instruksi;
    public javax.swing.JTextField isiPrihal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField jenisSurat;
    public javax.swing.JTextField noSurat;
    public javax.swing.JTextField pendisposisian;
    private javax.swing.JPanel pnDisposisi;
    private javax.swing.JComboBox<String> statusSurat;
    public com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JTextField tujuanDisposisi;
    // End of variables declaration//GEN-END:variables
}
